version: '2'
services:
  middleman-server:
    build: .
    command: bitrise run up-middleman-server
    volumes:
      - nsync_wfe:/bitrise/src
    ports:
      - "4567:4567"
      - "35729:35729"
  api-server:
    command: bitrise run up-api
    build:
      context: .
      dockerfile: Dockerfile-api
    volumes:
      - nsync_wfe:/bitrise/go/src/github.com/bitrise-io/bitrise-workflow-editor
    ports:
      - "1234:1234"
    environment:
      - MIDDLEMAN_SERVER_HOST=middleman-server
    depends_on:
      - "middleman-server"

volumes:
  nsync_wfe:
    external: true
