[[constraint]]
  name = "github.com/GeertJohan/go.rice"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/bitrise"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/depman"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/envman"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/stepman"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.8"

[prune]
  go-tests = true
  unused-packages = true
