release:
  development_branch: master
  release_branch: master
changelog:
  path: CHANGELOG.md
  content_template: |-
    {{range $index, $element := .ContentItems}}{{if eq $index 0}}{{range .Commits}}* {{.Message}}
    {{end}}

    For more information about the new Workflow Editor and how to install it, visit:
    https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2/39
    {{end}}{{end}}
