release:
  development_branch: master
  release_branch: master
changelog:
  path: CHANGELOG.md
  content_template: |-
    {{range $index, $element := .ContentItems}}{{if eq $index 0}}### Release Notes

    {{range $commitIndex, $commitElement := .Commits}}{{if gt $commitIndex 0}}* {{.Message}}
    {{end}}{{end}}

    ### Install or upgrade

    To install this version, run the following commands (in a bash shell):

    ```
    bitrise plugin install --source https://github.com/bitrise-io/bitrise-workflow-editor.git --version {{.EndTaggedCommit.Tag}}
    ```

    To update the already installed plugin to the latest version:

    ```
    bitrise plugin update workflow-editor
    ```

    That's all, you're ready to go!

    To run the workflow editor plugin call:

    ```
    bitrise :workflow-editor
    ```
    {{end}}{{end}}
